### Storage-Definition, define it as you need it:
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-zbx-externalscripts
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: YourStorageClass-Name
  resources:
    requests:
      storage: 10Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-zbx-mibs
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: YourStorageClass-Name
  resources:
    requests:
      storage: 100Mi
###########################################################################
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-proxy-sqlite3
  labels:
    app: zabbix
    tier: proxy
  namespace: default
spec:
  serviceName: zabbix-proxy-sqlite3
  replicas: 2
  minReadySeconds: 3
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: zabbix-proxy-sqlite3
      app: zabbix
  template:
    metadata:
      labels:
        name: zabbix-proxy-sqlite3
        app: zabbix
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: proxy-sqlite-data
          emptyDir: {}
        - name: mnt-externalscripts
          persistentVolumeClaim:
             claimName: pvc-zbx-externalscripts
        - name: mnt-mibs
          persistentVolumeClaim:
             claimName: pvc-zbx-mibs
      containers:
        - name: zabbix-proxy-sqlite3
          #image: zabbix/zabbix-proxy-sqlite3:alpine-5.4-latest
          image: Your-Repository:Port/zabbix-proxy-sqlite3-py3:alpine-5.4-latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 10051
            protocol: TCP
            name: zabbix-trapper
          startupProbe:
            tcpSocket:
              port: 10051
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 40
          livenessProbe:
            tcpSocket:
              port: 10051
            timeoutSeconds: 3
            failureThreshold: 3
            periodSeconds: 10
          env:
          - name: ZBX_PROXYMODE
            value: "0"
          - name: ZBX_SERVER_HOST
            value: "YOUR-ZABBIX-SERVER-Name/-IP"
          - name: ZBX_SERVER_PORT
            value: "10051"
          - name: ZBX_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
            #value: "zabbix-proxy-sqlite"
          - name: ZBX_ENABLEREMOTECOMMANDS
            value: "1"
          - name: ZBX_LOGREMOTECOMMANDS
            value: "1"
          - name: ZBX_HOSTNAMEITEM
            value: ""
          - name: ZBX_DEBUGLEVEL
            value: "3"
          - name: ZBX_PROXYLOCALBUFFER
            value: ""
          - name: ZBX_PROXYOFFLINEBUFFER
            value: ""
          - name: ZBX_PROXYHEARTBEATFREQUENCY
            value: "60"
          - name: ZBX_CONFIGFREQUENCY
            value: "3600"
          - name: ZBX_DATASENDERFREQUENCY
            value: "1"
          - name: ZBX_STARTPREPROCESSORS
            value: "3"
          - name: ZBX_STARTPOLLERS
            value: ""
          - name: ZBX_IPMIPOLLERS
            value: ""
          - name: ZBX_STARTPOLLERSUNREACHABLE
            value: ""
          - name: ZBX_STARTTRAPPERS
            value: ""
          - name: ZBX_STARTPINGERS
            value: "1"
          - name: ZBX_STARTDISCOVERERS
            value: ""
          - name: ZBX_STARTHISTORYPOLLERS
            value: "1"
          - name: ZBX_STARTHTTPPOLLERS
            value: ""
          - name: ZBX_JAVAGATEWAY_ENABLE
            value: "true"
          - name: ZBX_JAVAGATEWAY
            value: "zabbix-java-gateway"
          - name: ZBX_JAVAGATEWAYPORT
            value: "10052"
          - name: ZBX_STARTJAVAPOLLERS
            value: "5"
          - name: ZBX_STARTVMWARECOLLECTORS
            value: ""
          - name: ZBX_VMWAREFREQUENCY
            value: ""
          - name: ZBX_VMWAREPERFFREQUENCY
            value: ""
          - name: ZBX_VMWARECACHESIZE
            value: ""
          - name: ZBX_VMWARETIMEOUT
            value: ""
          - name: ZBX_ENABLE_SNMP_TRAPS
            value: "false"
          - name: ZBX_HOUSEKEEPINGFREQUENCY
            value: ""
          - name: ZBX_CACHESIZE
            value: "16M"
          - name: ZBX_STARTDBSYNCERS
            value: "4"
          - name: ZBX_HISTORYCACHESIZE
            value: "16M"
          - name: ZBX_HISTORYINDEXCACHESIZE
            value: "4M"
          - name: ZBX_TIMEOUT
            value: "15"
          - name: ZBX_TRAPPERIMEOUT
            value: ""
          - name: ZBX_UNREACHABLEPERIOD
            value: ""
          - name: ZBX_UNAVAILABLEDELAY
            value: ""
          - name: ZBX_UNREACHABLEDELAY
            value: ""
          - name: ZBX_LOGSLOWQUERIES
          - name: ZBX_LOADMODULE
            value: ""
          - name: ZBX_TLSCONNECT
            value: "unencrypted"
          - name: ZBX_TLSACCEPT
            value: "unencrypted"
          - name: ZBX_TLSCAFILE
            value: ""
          - name: ZBX_TLSCRLFILE
            value: ""
          - name: ZBX_TLSSERVERCERTISSUER
            value: ""
          - name: ZBX_TLSSERVERCERTSUBJECT
            value: ""
          - name: ZBX_TLSCERTFILE
            value: ""
          - name: ZBX_TLSKEYFILE
            value: ""
          - name: ZBX_TLSPSKIDENTITY
            value: ""
          - name: ZBX_TLSPSKFILE
            value: ""
          - name: ZBX_TLSCIPHERALL
            value: ""
          - name: ZBX_TLSCIPHERALL13
            value: ""
          - name: ZBX_TLSCIPHERCERT
            value: ""
          - name: ZBX_TLSCIPHERCERT13
            value: ""
          - name: ZBX_TLSCIPHERPSK
            value: ""
          - name: ZBX_TLSCIPHERPSK13
            value: ""
          - name: DEBUG_MODE
            value: "false"
          volumeMounts:
          - mountPath: "/var/lib/zabbix/db_data"
            name: proxy-sqlite-data
          - mountPath: "/usr/lib/zabbix/externalscripts"
            name: mnt-externalscripts
          - mountPath: "/var/lib/zabbix/mibs"
            name: mnt-mibs
          securityContext:
            capabilities: {}
            privileged: false
